### PR TITLE
Add decimal support

### PR DESCRIPTION
**Pull request by Anon-136**
* Use initial value instead to solve `onInput` decimal problem
Screenshot 2566-02-07 at 15 02 52

### CODE REVIEW

**Comment by suphon-t** [comment]
It broke iOS keyboard. 😢
Let me try debugging. 

853E38E2-E73B-4D1F-8517-8E96063E9D0B

**Comment by suphon-t** [comment]
Looks like using `inputmode="decimal"` instead of pattern works. Can you try on Android as well?

**Comment by Anon-136** [comment]
Added, also reverted
Working fine on android lmao

**Comment by suphon-t** [comment]
Merged. Thanks a lot! 🎉

**Pull request merged**
